[project]
name = "from-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "numpy>=2.3.4",
    "polars>=1.35.1",
    "scikit-learn>=1.7.2",
    "statsmodels>=0.14.5",
    "tqdm>=4.67.1",
]
